-- Backfill de una sola vez: las noticias insertadas antes de que existiera la
-- columna zona quedaron con zona = null. Les asignamos zona buscando nombres
-- de ciudad conocidos en el titulo/descripcion (mismo mapeo que
-- detectarZonaPorCiudad() en src/lib/sources.ts). Solo toca filas con zona null.
update noticias
set zona = case
  when titulo ilike '%la guaira%' or descripcion ilike '%la guaira%' then 'la_guaira'
  when titulo ilike '%catia la mar%' or descripcion ilike '%catia la mar%' then 'la_guaira'
  when titulo ilike '%maiquet%' or descripcion ilike '%maiquet%' then 'la_guaira'
  when titulo ilike '%los teques%' or descripcion ilike '%los teques%' then 'miranda'
  when titulo ilike '%guarenas%' or descripcion ilike '%guarenas%' then 'miranda'
  when titulo ilike '%guatire%' or descripcion ilike '%guatire%' then 'miranda'
  when titulo ilike '%petare%' or descripcion ilike '%petare%' then 'miranda'
  when titulo ilike '%charallave%' or descripcion ilike '%charallave%' then 'miranda'
  when titulo ilike '%puerto cabello%' or descripcion ilike '%puerto cabello%' then 'carabobo'
  when titulo ilike '%valencia%' or descripcion ilike '%valencia%' then 'carabobo'
  when titulo ilike '%guacara%' or descripcion ilike '%guacara%' then 'carabobo'
  when titulo ilike '%naguanagua%' or descripcion ilike '%naguanagua%' then 'carabobo'
  when titulo ilike '%san felipe%' or descripcion ilike '%san felipe%' then 'yaracuy'
  when titulo ilike '%chivacoa%' or descripcion ilike '%chivacoa%' then 'yaracuy'
  when titulo ilike '%yaritagua%' or descripcion ilike '%yaritagua%' then 'yaracuy'
  when titulo ilike '%moron%' or descripcion ilike '%moron%' then 'yaracuy'
  when titulo ilike '%la victoria%' or descripcion ilike '%la victoria%' then 'aragua'
  when titulo ilike '%maracay%' or descripcion ilike '%maracay%' then 'aragua'
  when titulo ilike '%cagua%' or descripcion ilike '%cagua%' then 'aragua'
  when titulo ilike '%turmero%' or descripcion ilike '%turmero%' then 'aragua'
  when titulo ilike '%maracaibo%' or descripcion ilike '%maracaibo%' then 'zulia'
  when titulo ilike '%cabimas%' or descripcion ilike '%cabimas%' then 'zulia'
  when titulo ilike '%ciudad ojeda%' or descripcion ilike '%ciudad ojeda%' then 'zulia'
  when titulo ilike '%barquisimeto%' or descripcion ilike '%barquisimeto%' then 'lara'
  when titulo ilike '%carora%' or descripcion ilike '%carora%' then 'lara'
  when titulo ilike '%punto fijo%' or descripcion ilike '%punto fijo%' then 'falcon'
  when titulo ilike '%coro%' or descripcion ilike '%coro%' then 'falcon'
  when titulo ilike '%san cristobal%' or descripcion ilike '%san cristobal%' then 'tachira'
  when titulo ilike '%el vigia%' or descripcion ilike '%el vigia%' then 'merida'
  when titulo ilike '%merida%' or descripcion ilike '%merida%' then 'merida'
  when titulo ilike '%valera%' or descripcion ilike '%valera%' then 'trujillo'
  when titulo ilike '%barinas%' or descripcion ilike '%barinas%' then 'barinas'
  when titulo ilike '%guanare%' or descripcion ilike '%guanare%' then 'portuguesa'
  when titulo ilike '%acarigua%' or descripcion ilike '%acarigua%' then 'portuguesa'
  when titulo ilike '%san carlos de austria%' or descripcion ilike '%san carlos de austria%' then 'cojedes'
  when titulo ilike '%san juan de los morros%' or descripcion ilike '%san juan de los morros%' then 'guarico'
  when titulo ilike '%calabozo%' or descripcion ilike '%calabozo%' then 'guarico'
  when titulo ilike '%san fernando de apure%' or descripcion ilike '%san fernando de apure%' then 'apure'
  when titulo ilike '%puerto la cruz%' or descripcion ilike '%puerto la cruz%' then 'anzoategui'
  when titulo ilike '%lecher%' or descripcion ilike '%lecher%' then 'anzoategui'
  when titulo ilike '%el tigre%' or descripcion ilike '%el tigre%' then 'anzoategui'
  when titulo ilike '%barcelona%' or descripcion ilike '%barcelona%' then 'anzoategui'
  when titulo ilike '%carupano%' or descripcion ilike '%carupano%' then 'sucre'
  when titulo ilike '%cumana%' or descripcion ilike '%cumana%' then 'sucre'
  when titulo ilike '%maturin%' or descripcion ilike '%maturin%' then 'monagas'
  when titulo ilike '%porlamar%' or descripcion ilike '%porlamar%' then 'nueva_esparta'
  when titulo ilike '%isla de margarita%' or descripcion ilike '%isla de margarita%' then 'nueva_esparta'
  when titulo ilike '%ciudad guayana%' or descripcion ilike '%ciudad guayana%' then 'bolivar'
  when titulo ilike '%puerto ordaz%' or descripcion ilike '%puerto ordaz%' then 'bolivar'
  when titulo ilike '%ciudad bolivar%' or descripcion ilike '%ciudad bolivar%' then 'bolivar'
  when titulo ilike '%puerto ayacucho%' or descripcion ilike '%puerto ayacucho%' then 'amazonas'
  when titulo ilike '%tucupita%' or descripcion ilike '%tucupita%' then 'delta_amacuro'
  when titulo ilike '%caracas%' or descripcion ilike '%caracas%' then 'distrito_capital'
  else zona
end
where zona is null;
